### ISSUE TITLE
Would you like to be included in an OpenTracing blog post?

### ISSUE THREAD

**Issue by pritianka** [gin-contrib/tracing#1]
Hi folks,

I am Priyanka and I work on the OpenTracing community. We are planning January recap blog post for the project where we will highlight cool community projects (in addition to other news). I saw your work with a Gin integration for OT and wanted to reach out and see if you'd like to be included. If you feel you have a lot more work to do before you show this off somewhere, totally understand. But if you are interested, would love to include you. Please let me know!

Best,
Priyanka

**Comment by xakep666** [comment]
Yes, please. What I need to do?

**Comment by pritianka** [comment]
Hi there, apologies for the late response. Please take a look at the "community contributions" section in this newsletter and provide me with a blurb similar to that for your project. Thank you! https://medium.com/opentracing/january-2018-opentracing-project-newsletter-a09c2db71a54
